# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Samantha Zhang
email: hello@samanthazhang.com
tagline: Product Designer & Builder
keywords: Samantha Zhang, Product Designer, UX Architect, Design Systems, B2B SaaS, Startup Founder, Data Visualization, User Experience, Bay Area
baseurl: "" # the subpath of your site, e.g. /blog
permalink: /projects/:title
url: "https://samanthazhang.com" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: moyicat
github_username:  moyicat
ogimg: /assets/img/og-img.png

# SASS
sass:
  sass_dir:          _sass
  style:            :compressed

# Feed
feed:
  path: atom.xml
author: Samantha Zhang

# Build settings
markdown: kramdown
theme: null
gems:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-redirect-from
exclude:
  - Gemfile
  - Gemfile.lock
